name: Dependency Analysis

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dependency-analysis:
    uses: crowdin/.github/.github/workflows/dependency-analysis.yml@main
    secrets:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
